<footer class="d-flex flex-wrap justify-content-between align-items-center border-top bg-light">
    <ul class="nav col-md-4 fs-4 ">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-dark">Contact Us</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-dark">Legal Information</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-dark">Cookies</a></li>
    </ul>
    <p class="col-md-4 mb-0 text-muted justify-content-end fs-4">Copyright © SOLUS 2021   Solus name and logos are registered trademarks</p>
</footer>
