<!--<link rel="stylesheet" type="text/css" href="<?php /*echo $block->getViewFileUrl('css/navbar.css')*/?>">
-->
<nav class="navbar mx-5 my-5 navbar-expand-sm navbar-light bg-faded">
    <div class="container-fluid">
        <a class="navbar-brand" href="/magento2"><img src='<?php echo $this->getViewFileUrl('images/logo-black-8.png'); ?>' alt="image-icon" width="170" height="57"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav my-2 my-lg-0 navbar-nav-scroll ms-auto fs-4 fw-bold" style="--bs-scroll-height: 100px;">
                <li class="nav-item me-4">
                    <a class="nav-link active" aria-current="page" href="/magento2/services">Services</a>
                </li>
                <li class="nav-item me-4">
                    <a class="nav-link active" href="/magento2/chooseabulb">Choose A Bulb</a>
                </li>
                <li class="nav-item me-4">
                    <a class="nav-link active" aria-current="page" href="#">About Us</a>
                </li>
                <li class="nav-item me-4">
                    <a class="nav-link active" href="#">News</a>
                </li>
                <li class="nav-item me-4">
                    <a class="nav-link active" href="/magento2/planetfirst">planet first<img src='<?php echo $this->getViewFileUrl('images/planet_heart_icon.png'); ?>' alt="image-icon" width="17" height="5"></a>
                </li>
            </ul>
        </div>
    </div>
</nav>



