<br/>
<div class="container-fluid">
    <h1 class="text-light text-center">We care deeply <br> about the future <br> of our planet</h1>
<?php
for($j=0;$j<10;$j++)
{
    echo "<br/>";
}
/*for($i=0;$i<41;$i++)
{
    echo "<img src=" . $this->getViewFileUrl('images/checkboard.jpg') . " class='img-fluid' alt='image-icon'  }>";
}*/
?>
    <div style="height: 20px; background: url('<?php echo $this->getViewFileUrl('images/checkboard.jpg'); ?>'); background-repeat-x: repeat; background-size: contain;"></div>
  <!--  planet_image -->
    <div class="text-light text-center d-flex justify-content-center align-items-center" style="height: 520px; font-size: 40px;  background: url(<?php echo $this->getViewFileUrl('images/planet_first_image.jpg'); ?>) no-repeat center; background-size: cover;">
        <div style="background-color: rgba(0, 0, 0, 0.5); background-position: center; width: 100%; height: 100%; overflow: hidden; color:#fff;">
            <p style="margin-top: 10%;">We will always consider<br>the environmental impact<br>of everything we make<br>and do.</p>
        </div>
    </div>

    <div class="bg-light" style="padding: 30px 0px 60px;">
        <div class="container">
            <div class="row">
                <div class="text-center">
                    <div class="text-dark" style="font-size: 20px; font-weight: bold; padding: 20px 0px 10px;">Solus is Ireland cleanest greenest lighting company. We care about the planet so we make sure our bulbs light the world as sustainably as possible. We care deeply about the future of our world and that of our customers, so we have launched a key initiative and promise to ourselves and the world, which we call Planet First. This means we always consider the environmental impact of everything we make and do.</div>
                    <div class="text-center"><?php echo "<img src=" . $this->getViewFileUrl('images/planet_heart_icon.jpg') . " alt='image-icon'  }>"; ?>
                        <div class="text-dark" style="font-size: 20px;">Our Latest Initiatives</div>
                        <div class="d-flex justify-content-around" style="padding: 40px 30px 0px 30px;">
                            <div class="text-left" style="width: 46%; font-size: 20px;"><?php echo "<img src=" . $this->getViewFileUrl('images/solus_initiative_4.jpg') . " alt='image-icon'  }>"; ?>
                                <div class="text-dark" style="font-weight: bold; padding: 20px 0px 10px;">Sustainability</div>
                                <p class="text-dark">Sustainability is a guiding principal of everything we do. Our new Solus packaging is 100% recyclable, with reduced footprint and use of materials across the range. Solus are committed to continue to lead the way in Sustainability in the lighting industry. Over the last five years, Solus has changed more than any other lighting company, as we rolled out a series of digital and customer experience improvements.</p>
                                <a class="text-dark text-decoration-none" href="#"><strong>Read More</strong></a></div>
                            <div class="text-left" style="width: 46%; font-size: 20px;"><?php echo "<img src=" . $this->getViewFileUrl('images/solus_initiative_2.jpg') . " alt='image-icon'  }>"; ?>
                                <div class="text-dark" style="font-weight: bold; padding: 20px 0px 10px;">Green Logistics</div>
                                <p class="text-dark">Solus are at the forefront of actual sustainable initiatives by using the world’s only TÜV-certified emission calculation which is innovation in action by providing ‘green logistics’ services. The software calculates relevant emissions based on the vehicle, weight and inclines. It calculates the most ‘green logistic routes’ throughout Ireland. Solus light bulbs are built to cover all the requirements of the International Standard ISO 9001 and we are active participants in the Energy Savings Trust and are members of WEEE Ireland and Repak.</p>
                            </div>
                        </div>
                        <div class="d-flex justify-content-around" style="padding: 40px 30px 0px 30px;">
                            <div class="text-left" style="width: 46%; font-size: 20px;"><?php echo "<img src=" . $this->getViewFileUrl('images/solus_initiative_1.jpg') . " alt='image-icon'  }>"; ?>
                                <div class="text-dark" style="font-weight: bold; padding: 20px 0px 10px;">The Solus Energy Lab</div>
                                <p class="text-dark">Solus has launched the Solus Energy Lab – an initiative around education, experience and energy awareness. Lighting technology is changing fast and as we move to the next generation, a key objective for Solus is around education, experience and creating energy awareness. As part of that strategy, various programs around Ireland will be held throughout the year through the Solus Energy Lab so we can continue to evolve our iconic Irish brand for the future.</p>
                            </div>
                            <div class="text-left" style="width: 46%; font-size: 20px;"><?php echo "<img src=" . $this->getViewFileUrl('images/solus_initiative_3.jpg') . " alt='image-icon'  }>"; ?>
                                <div class="text-dark" style="font-weight: bold; padding: 20px 0px 10px;">Do you have a bright idea?</div>
                                <p class="text-dark"> As a society, we can make choices that will avoid the serious consequences of global warming. There are simple choices that each one of us can make, like installing energy-saving light bulbs in our homes. And then there are choices that we can make together, like choosing leaders who take bold policy initiatives and a new mindset. Do you have a bright idea that you think will help us light the world as sustainably as possible.? We would love to hear from you!</p>
                                <a class="text-dark text-decoration-none" href="#"><strong>Let us know. Contact us. We'd love to hear from you.</strong></a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

