 <?php
    for($j=0;$j<5;$j++)
    {
        echo "<br/>";
    }
    ?>

<div class="container-fluid">
    <h1 class="text-light text-center">Innovation, ideas <br> & customer service.</h1>
    <?php
    for($j=0;$j<17;$j++)
    {
        echo "<br/>";
    }
    /*for($i=0;$i<41;$i++)
    {
        echo "<img src=" . $this->getViewFileUrl('images/checkboard.jpg') . " class='img-fluid' alt='image-icon'  }>";
    }*/
    ?>
    <div style="height: 20px; background: url('<?php echo $this->getViewFileUrl('images/checkboard.jpg'); ?>'); background-repeat-x: repeat; background-size: contain;"></div>
    <div class="bg-warning" style="padding: 65px 0px; font-size: 1.6rem;">
        <div class="container">
            <div class="row">
                <div class="text-dark text-center fw-bold">Solus is an Irish owned company that has been established for over eighty years. Renowed for its quality products they are used in a wide varity of application throughout industry and domestic households.</div>
                <div class="text-dark d-flex justify-content-between" style="margin-top: 65px;">
                    <p class="pe-5">We believe that light is life. It’s a vital human need and an essential feature of a thriving society. Our productivity and wellbeing depend on it. That’s why we take our role as Ireland’s lighting experts so seriously.</p>
                    <p>We approach lighting from a holistic, human perspective and then apply the best of our scientific and technical know-how to ensure our products are best-in-class. We’ve been gathering an in-depth understanding of our customer’s needs for generations, investing in research to inform our innovations. Our goal is to ensure no one in Ireland is ever wanting for light. We exist to light up life.</p>
                </div>
            </div>
        </div>
    </div>

    <div style="padding:60px 0px 30px; font-size: 1.6rem;">
        <div class="container">
            <div class="row">
                <h2 class="text-center" style="font-weight: bold; font-size: 30px;">Our Services</h2>
                <div class="d-flex" style=" flex-wrap: wrap; padding-top: 50px;">
                    <div class="bg-dark text-center" style="width: 33.33%; height: 250px; display: flex; flex-direction: column; justify-content: center;">
                        <p class="text-light" style="font-size: 30px; line-height: 35px; width: 200px; margin: 0px auto 5px;">Merchandising</p>
                        <a class="text-warning text-decoration-none" href="#">Read more</a></div>
                    <div class="text-center" style="background: #57585a; width: 33.33%; height: 250px; display: flex; flex-direction: column; justify-content: center;">
                        <p class="text-light" style="font-size: 30px; line-height: 35px; width: 200px; margin: 0px auto 5px;">Retail Services</p>
                        <a class="text-warning text-decoration-none" href="#">Read more</a></div>
                    <div class="bg-dark text-center" style="width: 33.33%; height: 250px; display: flex; flex-direction: column; justify-content: center;">
                        <p class="text-light" style="font-size: 30px; line-height: 35px; width: 200px; margin: 0px auto 5px;">Planagrams</p>
                        <a class="text-warning text-decoration-none" href="#">Read more</a></div>
                    <div class="text-center" style="background: #57585a; width: 33.33%; height: 250px; display: flex; flex-direction: column; justify-content: center;">
                        <p class="text-light" style="font-size: 30px; line-height: 35px; width: 200px; margin: 0px auto 5px;">Recycling Compliance</p>
                        <a class="text-warning text-decoration-none" href="#">Read more</a></div>
                    <div class="bg-dark text-center" style="width: 33.33%; height: 250px; display: flex; flex-direction: column; justify-content: center;">
                        <p class="text-light" style="font-size: 30px; line-height: 35px; width: 200px; margin: 0px auto 5px;">Sales</p>
                        <a class="text-warning text-decoration-none" href="#">Read more</a></div>
                    <div class="text-center" style="background: #57585a; width: 33.33%; height: 250px; display: flex; flex-direction: column; justify-content: center;">
                        <p class="text-light" style="font-size: 30px; line-height: 35px; width: 200px; margin: 0px auto 5px;">Point of Sale</p>
                        <a class="text-warning text-decoration-none" href="#">Read more</a></div>
                </div>
            </div>
        </div>
    </div>

</div>
